{
 "title": "K6 Prome Load Test",
 "description": "with Native Histograms - v1",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "testid", "label": "Test ID", "query": { "query": "label_values(testid)" } }
  ]
 },
 "panels": [
  {
   "title": "Total Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "k6_data_received_total{testid=~\"$testid\"}",
     "legendFormat": "Received"
    },
    {
     "expr": "k6_data_sent_total{testid=~\"$testid\"}",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Data per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(k6_data_received_total{testid=~\"$testid\"}[$__rate_interval])",
     "legendFormat": "Received"
    },
    {
     "expr": "irate(k6_data_sent_total{testid=~\"$testid\"}[$__rate_interval])",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(sum(k6_http_reqs_total{testid=~\"$testid\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP Requests Succees",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(sum(k6_http_reqs_total{testid=~\"$testid\",expected_response=~\"true\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP Requests Failures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(sum(k6_http_reqs_total{testid=~\"$testid\",expected_response=~\"false\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Highest HTTP Request per Second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg HTTP Request per Second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lowest HTTP Request per Second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VUs & All HTTP Request per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "VUs" } },
   "targets": [
    {
     "expr": "k6_vus{testid=~\"$testid\"}",
     "legendFormat": "vus"
    },
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "all_http_req"
    },
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\",expected_response=~\"false\"}[$__rate_interval]))",
     "legendFormat": "http_req_failed"
    }
   ]
  },
  {
   "title": "Success Request Stats",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "histogram_quantile(0, sum by(le, name, method, status) (rate(k6_http_req_duration_seconds{testid=~\"$testid\",expected_response=~\"true\"}[$__rate_interval])))",
     "legendFormat": "min"
    },
    {
     "expr": "histogram_quantile(1, sum by(le, name, method, status) (rate(k6_http_req_duration_seconds{testid=~\"$testid\",expected_response=~\"true\"}[$__rate_interval])))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, name, method, status) (rate(k6_http_req_duration_seconds{testid=~\"$testid\",expected_response=~\"true\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, name, method, status) (rate(k6_http_req_duration_seconds{testid=~\"$testid\",expected_response=~\"true\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Requests Endpoint",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by (url) (k6_http_reqs_total{testid=~\"$testid\",status=~\"0\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (url) (k6_http_reqs_total{testid=~\"$testid\",status=~\"5.+\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (url) (k6_http_reqs_total{testid=~\"$testid\",status=~\"4.+\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}