spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:concert-reservation
    username: lowell
    password: lowell

  data:
    redis:
      host: localhost
      port: 6379

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true

concert:
  api:
    logging:
      enable: true

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE
        cache: TRACE