spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/concert_reservation
    username: root
    password: root

  data:
    redis:
      host: redis
      port: 6379
    cache:
      type: redis

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  prometheus:
    metrics:
      export:
        enabled: true